### PR TITLE
[202211] Revert "Ignore removing switch for mellanox platform due to known limitation (#1216)"

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
What I did?

This reverts commit 62aa2448328f50815336561e141d076cf03d4087.

Why I did this?

This commit introduces a race condition with would cause syncd crash. The issue happens when:

Syncd.m_sn has been freed
SAI send a port state change notification which will access Syncd.m_sn ===> causes crash

### CODE REVIEW

**Review by kcudnik — APPROVED** [review]

**Comment by keboliu** [comment]
@StormLiangMS  would you please help merge?

**Pull request merged**
