### PR TITLE
Skip FABRIC PORT Attributes from sairedis logging (Issue 17583 )

### PR DESCRIPTION
**Pull request by saksarav-nokia**
Orchagent polls SAI_PORT_ATTR_FABRIC_ATTACHED, SAI_PORT_ATTR_FABRIC_ATTACHED_SWITCH_ID & SAI_PORT_ATTR_FABRIC_ATTACHED_PORT_INDEX attributes  every 30 secs for all the fabric ports in  Supervisor and Linecards.
If there are many asics in SUP and LC, these logs fill up the sairedis records very quickly and take up the disk space. Since these logs don't give much useful information, added these attributes  SkipRecordAttrContainer to skip them from sairedis logging.

Fix for https://github.com/sonic-net/sonic-buildimage/issues/17583

### CODE REVIEW

**Comment by judyjoseph** [comment]
@saksarav-nokia Please add the test details too .. To confirm the logs are no more coming in the sairedis logs

**Review by judyjoseph — APPROVED** [review]
LGTM

**Comment by saksarav-nokia** [comment]
@judyjoseph , i tested the fix in both SUP and LC and monitored the sairedis logs, these logs are not getting logged.  Without this change, the sairedis logs used to fill very quickly and log rotate rotates the sairedis files and many files will be present with in few hours. But with this fix, only very few sairedis log files are present and the events are created only during syncd init and not the regular polling events.

**Review by kcudnik — APPROVED** [review]

**Comment by StormLiangMS** [comment]
@judyjoseph could we have an ADO for cherry pick?

**Comment by judyjoseph** [comment]
@kcudnik I have a quick question here -- these attributes  SAI_PORT_ATTR_FABRIC_ATTACHED, SAI_PORT_ATTR_FABRIC_ATTACHED_SWITCH_ID & SAI_PORT_ATTR_FABRIC_ATTACHED_PORT_INDEX -- are specific to T2 not applicable to T0/T1. Do we need to add any T2 specific check for these attributes inSkipRecordAttrContainer::SkipRecordAttrContainer() ?

**Comment by kcudnik** [comment]
im not ware of any specific platform attributes, and i dont have enough knowledge here, can you ask @saksarav-nokia

**Comment by saksarav-nokia** [comment]
@judyjoseph @kcudnik , The daemon FabricPortsOrch is started only if m_fabricEnabled is set and this flag is set only if the switch is voq. Do we still need to add  T2 only check in SkipRecordAttrContainer?
  if (gMySwitchType != "fabric")
    {
        orchDaemon = make_shared<OrchDaemon>(&appl_db, &config_db, &state_db, chassis_app_db.get());
        if (gMySwitchType == "voq")
        {
            orchDaemon->setFabricEnabled(true);
            orchDaemon->setFabricPortStatEnabled(true);
            orchDaemon->setFabricQueueStatEnabled(false);
        }
    }


if (m_fabricEnabled)
    {
        vector<table_name_with_pri_t> fabric_port_tables = {
           // empty for now
        };
        gFabricPortsOrch = new FabricPortsOrch(m_applDb, fabric_port_tables, m_fabricPortStatEnabled, m_fabricQueueStatEnabled);
        m_orchList.push_back(gFabricPortsOrch);
    }

**Comment by kcudnik** [comment]
Not sure about that, could you ask author of that enable fabric code ? I didn't put that there

**Comment by gechiang** [comment]
@StormLiangMS , @yxieca ,
MSFT ADO: 26734247
Please help approve backport to 202205, 202305, and 202311.
Thanks!

**Comment by gechiang** [comment]
@yxieca this PR was approved for 202205 but I don't see this ever made it into 202205.  Did this missed by auto-cherry-pick somehow?  Can you help check what happened?
Thanks!

**Comment by yxieca** [comment]
> @yxieca this PR was approved for 202205 but I don't see this ever made it into 202205. Did this missed by auto-cherry-pick somehow? Can you help check what happened? Thanks!

@liushilongbuaa can you take a look?

**Comment by liushilongbuaa** [comment]
@gechiang , @yxieca  please create separate PR to cherry pick if urgent.

**Pull request merged**
