### PR TITLE
Debug commit to trigger azure ci

### PR DESCRIPTION
**Pull request by vadymhlushko-mlnx**

### CODE REVIEW

**Comment by kcudnik** [comment]
please add description

**Comment by kcudnik** [comment]
why you want to make this change ? seems like this is not needed

**Comment by vadymhlushko-mlnx** [comment]
> why you want to make this change ? seems like this is not needed

I just wanted to trigger `sonic-sairedis` `coverity` check for debugging purposes, the changes itself is not relevant

**Comment by kcudnik** [comment]
so is this just dummy PR ?

**Comment by vadymhlushko-mlnx** [comment]
> so is this just dummy PR ?

yes, I will close it

**Pull request closed without merging**
