### PR TITLE
[submodule] Update SAI to latest master

### PR DESCRIPTION
**Pull request by kcudnik**
To latest SAI v1.15.0

### CODE REVIEW

**Comment by kcudnik** [comment]
there is problem with swss becasue of backward compatibility issues:

```
g++ -DHAVE_CONFIG_H -I. -I../..  -g -DNDEBUG  -std=c++14 -Wall -fPIC -Wno-write-strings -I/usr/include/swss -I/usr/include/libnl3 -Werror -Wno-reorder -Wcast-align -Wcast-qual -Wconversion -Wdisabled-optimization -Wextra -Wfloat-equal -Wformat=2 -Wformat-nonliteral -Wformat-security -Wformat-y2k -Wimport -Winit-self -Winvalid-pch -Wlong-long -Wmissing-field-initializers -Wmissing-format-attribute -Wno-aggregate-return -Wno-padded -Wno-switch-enum -Wno-unused-parameter -Wpacked -Wpointer-arith -Wredundant-decls -Wstack-protector -Wstrict-aliasing=3 -Wswitch -Wswitch-default -Wunreachable-code -Wunused -Wvariadic-macros -Wno-switch-default -Wno-long-long -Wno-redundant-decls  -I /usr/include/sai -I ../../orchagent/flex_counter -I ../../orchagent/debug_counter -I ../../lib -I../../cfgmgr -I../../orchagent -I../../orchagent/p4orch/tests -I../../orchagent/dash -I../../warmrestart -Wdate-time -D_FORTIFY_SOURCE=2  -g -O2 -ffile-prefix-map=/__w/1/s=. -fstack-protector-strong -Wformat -Werror=format-security -c -o tests-warmrestarthelper_ut.o `test -f 'warmrestarthelper_ut.cpp' || echo './'`warmrestarthelper_ut.cpp
switchorch_ut.cpp: In member function 'virtual void switchorch_test::SwitchOrchTest_SwitchOrchTestHandleEvent_Test::TestBody()':
switchorch_ut.cpp:295:83: error: missing initializer for member '_sai_switch_health_data_t::data' [-Werror=missing-field-initializers]
  295 |         sai_switch_health_data_t data = {.data_type = SAI_HEALTH_DATA_TYPE_GENERAL};
      |                                                                                   ^
```

 because some fields in structs appear, current swss won't let it compile  because initializers are missing
similar will be for SER data and port_oper_status notification with port_error_status field :(

**Comment by kcudnik** [comment]
attempt to fix tests on swss: https://github.com/sonic-net/sonic-swss/pull/3321

**Comment by StormLiangMS** [comment]
hi @kcudnik  this PR caused issue on the master branch, could we revert?

**Comment by kcudnik** [comment]
Which master branch ?

**Pull request merged**
