### PR TITLE
Add Voqs to Virtual Switch (#1061)

### PR DESCRIPTION
**Pull request by skbarista**
* Add Voqs to Virtual Switch
* Add UnitTest.

### CODE REVIEW

**Comment by yxieca** [comment]
@skbarista  can you help check the check failures?

**Comment by skbarista** [comment]
@yxieca the failures are not related to my changes. I see other pr https://github.com/sonic-net/sonic-sairedis/pull/1159 also facing similar failures. I have restarted the tests

**Comment by skbarista** [comment]
"[2022-12-01 19:06:10] [build-stderr] In file included from defaultvalueprovider.cpp:10:
[2022-12-01 19:06:10] [build-stderr] defaultvalueprovider.h:8:10: fatal error: libyang/libyang.h: No such file or directory
[2022-12-01 19:06:10] [build-stderr]     8 | #include <libyang/libyang.h>
[2022-12-01 19:06:10] [build-stderr]       |          ^~~~~~~~~~~~~~~~~~~
[2022-12-01 19:06:10] [build-stderr] compilation terminated.
[2022-12-01 19:06:10] [build-stderr] make[3]: *** [Makefile:809: libswsscommon_la-defaultvalueprovider.lo] Error 1
[2022-12-01 19:06:10] [build-stderr] make[3]: *** Waiting for unfinished jobs....
[2022-12-01 19:06:14] [build-stdout] make[3]: Leaving directory '/opt/src/sonic-swss-common/common'
[2022-12-01 19:06:14] [build-stderr] make[2]: *** [Makefile:440: all-recursive] Error 1
[2022-12-01 19:06:14] [build-stdout] make[2]: Leaving directory '/opt/src/sonic-swss-common'
[2022-12-01 19:06:14] [build-stdout] make[1]: Leaving directory '/opt/src/sonic-swss-common'
[2022-12-01 19:06:14] [build-stderr] make[1]: *** [Makefile:372: all] Error 2
[2022-12-01 19:06:14] [build-stderr] dh_auto_build: error: make -j4 returned exit code 2
[2022-12-01 19:06:14] [build-stderr] make: *** [debian/rules:33: build] Error 25
[2022-12-01 19:06:14] [build-stderr] dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
[2022-12-01 19:06:14] [ERROR] Spawned process exited abnormally (code 2; tried to run: [/opt/work/lgtm-workspace/lgtm/extract.s"

The error is above. Looks to be an environment issue. sonic-sairedis build with the latest code passed.

**Comment by skbarista** [comment]
I messed up something when I tried to merge upstream. So closed this pr and created a new pr https://github.com/sonic-net/sonic-sairedis/pull/1162

**Pull request closed without merging**
