### PR TITLE
[azp] Fix swss missing libs

### PR DESCRIPTION
**Pull request by Pterosaur**
Swss containter needs dash_api to properly build, based on https://github.com/sonic-net/sonic-swss/pull/2722, attempting to add missing libs

### CODE REVIEW

**Comment by Pterosaur** [comment]
Wait PR: https://github.com/sonic-net/sonic-swss/pull/2878

**Comment by kcudnik** [comment]
test errors seems not related to the change

**Review by kcudnik — APPROVED** [review]

**Pull request merged**
