### PR TITLE
[submodule] Update SAI submodule to v1.13 

### PR DESCRIPTION
**Pull request by kcudnik**
Add needed changes and new files required by new SAI version

### CODE REVIEW

**Comment by kcudnik** [comment]
@prsunny Can you help me with those tests ? not sure why they fail

**Comment by kcudnik** [comment]
failing test is VOQ switch:

```
Sep 18 13:17:15.570793 7411e3e836e2 ERR #orchagent: :- meta_generic_validation_create: SAI_SWITCH_ATTR_SWITCH_ID:SAI_ATTR_VALUE_TYPE_UINT32 attribute is conditional and is mandatory but not passed in attr list
Sep 18 13:17:15.570801 7411e3e836e2 ERR #orchagent: :- main: Failed to create a switch, rv:-14
Sep 18 13:17:15.570805 7411e3e836e2 NOTICE #orchagent: :- notifySyncd: sending syncd: SYNCD_INVOKE_DUMP
Sep 18 13:17:15.571056 7411e3e836e2 NOTICE #syncd: :- processNotifySyncd: Invoking SAI failure dump
Sep 18 13:17:15.576231 7411e3e836e2 NOTICE #orchagent: :- sai_redis_notify_syncd: invoked DUMP succeeded
```

```
==================================== ERRORS ====================================
_____________ ERROR at setup of TestVirtualChassis.test_voq_switch _____________

tp = <class 'AssertionError'>, value = None, tb = None

    def reraise(tp, value, tb=None):
        try:
            if value is None:
                value = tp()
            if value.__traceback__ is not tb:
>               raise value.with_traceback(tb)

/usr/lib/python3/dist-packages/six.py:702: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
conftest.py:1843: in vst
    vct = DockerVirtualChassisTopology(vctns, imgname, keeptb, dvs_env, log_path, max_cpu,
conftest.py:1424: in __init__
    self.handle_request()
conftest.py:1519: in handle_request
    self.create_vct_ctn(ctndir)
conftest.py:1579: in create_vct_ctn
    self.dvss[ctnname] = DockerVirtualSwitch(name=None, imgname=self.imgname,
conftest.py:415: in __init__
    self.check_ready_status_and_init_db()
conftest.py:469: in check_ready_status_and_init_db
    self.check_services_ready()
conftest.py:507: in check_services_ready
    wait_for_result(_polling_function, service_polling_config)
```

**Comment by kcudnik** [comment]
this is the issue:
https://github.com/opencomputeproject/SAI/compare/1761e2f721ecc5295898b457465cf3abc3adaf96...7f7a7587debf6b393118b29ca71c2d00722bb885#diff-8461e6438fb46cfa3d81a0760d680f8e5ac38c57da553a8f9add2fa3ffde3549R2500

**Comment by kcudnik** [comment]
Because of this change: [https://github.com/opencomputeproject/SAI/pull/1793/files#diff-8461e6438fb46cfa3d81a0760d680f8e5ac38c57da553a8f9add2fa3ffde3549R2500](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fopencomputeproject%2FSAI%2Fpull%2F1793%2Ffiles%23diff-8461e6438fb46cfa3d81a0760d680f8e5ac38c57da553a8f9add2fa3ffde3549R2500&data=05%7C01%7Ckcudnik%40microsoft.com%7C649c37e834a242edb07408dbb869fba5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638306537569037240%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Y%2F%2B6w2uqWCuQ1U1k6QHGWH2rg3Nsj84T4QEfSUpyhro%3D&reserved=0)

SAI_SWITCH_ATTR_SWITCH_ID will be required when switch type is FABRIC, and this is somewhat breaking change, since suddenly metadata in SAI v1.13 will require this attribute, and to make this work, sairedis needs to update SAI v1.13 on master, which I added PR here: [https://github.com/sonic-net/sonic-sairedis/pull/1292](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsonic-net%2Fsonic-sairedis%2Fpull%2F1292&data=05%7C01%7Ckcudnik%40microsoft.com%7C649c37e834a242edb07408dbb869fba5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638306537569037240%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=I6AQ%2BAhaG7aedK6gaXf9yiCEL6uDIzO6ZHwF7DVY74o%3D&reserved=0) and it’s failing VOQ switch test, because metadata is requiring this attribute, and swss is not providing it

So solution to that is to merge sairedis with failing tests, and then update swss with PR that will also pass this attribute on FABRIC, then swss will pass, and then next PRs on sairedis will also pass

**Review by lguohan — APPROVED** [review]

**Comment by prsunny** [comment]
@kcudnik , could you merge this?

**Pull request merged**
