### PR TITLE
Fix pipeline issue caused by urllib3 v2

### PR DESCRIPTION
**Pull request by liushilongbuaa**
docker 4.4.1 don't support urllib3 v2.
Update it to latest.

### CODE REVIEW

**Review by kcudnik — APPROVED** [review]

**Comment by liuh-80** [comment]
@liushilongbuaa , ADO is missing, also the description not follow PR description template, please update. if this PR no need cherrk-pick to 202012 please remove the request for 202012 label.

**Comment by nazariig** [comment]
@prsunny would you please cherry-pick to 202211? It is SWSS CI blocker

**Comment by nazariig** [comment]
@prsunny / @yxieca just a kind reminder

**Comment by nazariig** [comment]
@kcudnik would you please help to cherry-pick to `202211`?

**Comment by kcudnik** [comment]
can you make PR for 202211 ?

**Pull request merged**
