### PR TITLE
Add Xsight specific syncd start options

### PR DESCRIPTION
**Pull request by deran1980**
Signed-off-by: Roman Zhurakivsky <rzhurak@larch-networks.com>

**What I did**
Added xsight platform specific options for syncd common

**How I did it**

Modify syncd_init_common.sh script. added a function to support xsight based platforms. 

**How to verify it**
Verify on Accton platform (based on Xsight ASIC)

### CODE REVIEW

**Review by kcudnik — APPROVED** [review]

**Comment by deran1980** [comment]
Hi @kcudnik  - is it going to be merged or we need to wait for sairedis master branch to pass all pipelines tests?

**Comment by deran1980** [comment]
Guess not... 
I can try helping review the failures but it was not introduced as part of this PR.

**Comment by deran1980** [comment]
Hi @kcudnik - I ran the jobs several times and it seems very unstable. 
it always fails as you can see, but every time it fails on different test cases. 
is there a general issue with the stability of the tests or this is a real issue in current master tests that needs to be fixed?
the reason I am asking is because I can see from time to time that there are PRs which are able to pass all tests.

**Comment by kcudnik** [comment]
yes, those test could be very unstable, rest is good so i approve and you can merge

**Comment by deran1980** [comment]
Hi @kcudnik thanks!
But I don't think I have permission to perform merge so I will appreciate if you can merge it. 
Thanks.

**Pull request merged**
