### PR TITLE
[syncd] Enable bulk api for next hop objects

### PR DESCRIPTION
**Pull request by Ndancejic**
swss code change in 202411 uses nexthop bulk api to process dualtor mux switchover. Adds support in syncd for nexthop bulk api, which is present in SAI.

Currently blocking 202411 and master branch merges for swss. Needs to be backported to 202411 as well.

### CODE REVIEW

**Comment by Ndancejic** [comment]
@kcudnik please help review and add request tag for 202411 branch as well, thanks in advance!

this change is needed to unblock swss submodule update PR to buildimage

@prsunny for visibility

https://github.com/sonic-net/sonic-buildimage/pull/21002
https://github.com/sonic-net/sonic-buildimage/pull/21167

**Review by kcudnik — DISMISSED** [review]

**Comment by kcudnik** [comment]
please fix tests

**Comment by Ndancejic** [comment]
Hi @kcudnik all checks are passing now, please help merge when available

**Review by prsunny — APPROVED** [review]

**Comment by prsunny** [comment]
Merging based on Kamil's previous approval and unblock submodule update

**Pull request merged**
