### PR TITLE
* Add Voqs to Virtual Switch

### PR DESCRIPTION
**Pull request by skbarista**
* Add Voqs to Virtual Switch
* Add UnitTest.
* Port https://github.com/sonic-net/sonic-sairedis/pull/1135 to 202205
  to fix lgtm.

### CODE REVIEW

**Comment by kenneth-arista** [comment]
@arlakshm This PR needs to merge first before the corresponding swss PR can be raise to enable test coverage in 202205

**Comment by xumia** [comment]
Merged the PR by force to unblock build error in multiple repositories: sonic-swss-common, sonic-sairedis, sonic-swss.

**Pull request merged**
