### PR TITLE
[202205]Use SAI_STATUS_ITEM_NOT_FOUND when key not found (#1224)

### PR DESCRIPTION
**Pull request by theasianpianist**
* Use SAI_STATUS_ITEM_NOT_FOUND when key not found
* Add unit tests for Meta SAI validation
* generate coverage info for Meta.cpp

### CODE REVIEW

**Comment by andriy-kokhan** [comment]
I believe CI is failing because of missing fix here https://github.com/sonic-net/sonic-sairedis/blob/5808260e8a5d9b432313a950905df8b11b8dd713/meta/Meta.cpp#L3621

**Comment by prsunny** [comment]
Thanks @andriy-kokhan , @theasianpianist , can you check?

**Review by kcudnik — APPROVED** [review]

**Comment by theasianpianist** [comment]
Waiting for #1238 to be cherry-picked to 202205

**Pull request merged**
