### PR TITLE
[doc]: Update README.md

### PR DESCRIPTION
**Pull request by mdanish-kh**
### What I did
- Fixed build URL and added Azure build URLs for each branch.
- Update old URLs
- General typo/grammar fix

### CODE REVIEW

**Comment by mdanish-kh** [comment]
@kcudnik Can you please review?

**Review by kcudnik — DISMISSED** [review]

**Comment by kcudnik** [comment]
not sure why those builds fail, it's just readme file

**Comment by mdanish-kh** [comment]
Closed and re-opened the PR to re-run the pipelines, but it is still failing.

**Comment by mdanish-kh** [comment]
The unit tests are repeatedly failing.

**Comment by kcudnik** [comment]
can you try to do a force push on this branch with empty commit to retriger all build ?
those should not fail at all when changing readme

**Comment by mdanish-kh** [comment]
> can you try to do a force push on this branch with empty commit to retriger all build ? those should not fail at all when changing readme

@kcudnik  I believe closing and re-opening the PR does the same. It re-runs the pipelines. I have been doing this for a few days, everytime the checks fail on the unittests in pipelines.

**Comment by kcudnik** [comment]
this is wired since other PR's are passing on tests, for example this one https://github.com/sonic-net/sonic-sairedis/pull/1132 which was posted later

**Comment by mdanish-kh** [comment]
> this is wired since other PR's are passing on tests, for example this one #1132 which was posted later

The same test i.e., `Sairedis build (amd64)` passes in my other PR in sonic-swss-common repo https://github.com/sonic-net/sonic-swss-common/pull/696/checks?check_run_id=8670553168, I don't know whether some tests are different here that does not make it pass here.

**Comment by kcudnik** [comment]
here:
```
../README.md:The SAI Redis provides a SAI redis service built on top of redis database. It contains two major components: 
ERROR: some files contain white spaces at the end of line, please fix
FAIL: checkwhitespace.sh

```

**Comment by mdanish-kh** [comment]
@kcudnik Thanks for pointing this out! Didn't realize a trailing white space causes issues in the pipelines, will keep this in mind in the future. 

All checks have passed now. Could you please review again?

**Review by kcudnik — APPROVED** [review]

**Pull request merged**
