### PR TITLE
[nvidia] Update syncd start script to cover changes in SDK initialization process. 

### PR DESCRIPTION
**Pull request by oleksandrivantsiv**
- Create a folder for SDK dumps based on the SDK_DUMP_PATH variable from the SAI profile file.
- Update the number of huge pages required to run SDK. 
- Customise interfaces configuration based on SKU

### CODE REVIEW

**Comment by oleksandrivantsiv** [comment]
@kcudnik can you please review the PR?

**Review by kcudnik — APPROVED** [review]

**Comment by oleksandrivantsiv** [comment]
@kcudnik can you please merge the PR?

**Comment by kcudnik** [comment]
Please add description to PR

**Review by kcudnik — APPROVED** [review]

**Comment by oleksandrivantsiv** [comment]
@kcudnik can we merge the PR?

**Comment by kcudnik** [comment]
Create a folder for SDK dumps based on the SDK_DUMP_PATH variable from the SAI profile file.
Update the number of huge pages required to run SDK.
Customise interfaces configuration based on SKU

**Pull request merged**
