### PR TITLE
[Mellanox] Resolve New Line Formatting Issues in syncd's sai.profile

### PR DESCRIPTION
**Pull request by tshalvi**
On Mellanox platforms, the /tmp/sai.profile file inside syncd might end up with invalid formatting after running the script modified by this PR, such as missing new lines after concatenation or redundant new lines. This PR aims to fix that.

### CODE REVIEW

**Review by noaOrMlnx — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@kcudnik could you please help to review and merge?

**Comment by liat-grozovik** [comment]
@kcudnik @saiarcot895 can you please help to merge?
then we need it on 202405 @bingwang-ms  to follow up

**Review by prgeor — APPROVED** [review]

**Review by kcudnik — APPROVED** [review]

**Comment by yanmo96** [comment]
Thanks, the `echo >> /tmp/sai-temp.profile` fix when the file is missing a line feed at the end issue

**Comment by bingwang-ms** [comment]
Do a manual cherry-pick as the automation is not working https://github.com/sonic-net/sonic-sairedis/pull/1433
@dprital Can you check if the PR is required for 202311 branch? I didn't see issue in 202311.
@yxieca FYI

**Pull request merged**
