### PR TITLE
[202405][syncd] Enable bulk api for neighbor entries

### PR DESCRIPTION
**Pull request by Ndancejic**
SAI 1.11.0 added support for bulk neighbor entries. Adding support for neighbor bulk operations to syncd.

cherry-pick of https://github.com/sonic-net/sonic-sairedis/pull/1373. which includes the commits below:

commit 57b8e6f6a43efdd252fe4cdaaf9d93178c76f620 (HEAD -> ndancejic202405, dancejic/ndancejic202405, 202405)
Author: Nikola Dancejic <ndancejic@microsoft.com>
Date:   Tue May 14 18:23:55 2024 +0000

    [syncd] Enable bulk api for neighbor entries
    
    SAI 1.11.0 added support for bulk neighbor entries. Adding support for
    neighbor bulk operations to syncd.
    * added neighbor entry capability to bulk operations in syncd
    * added unit tests for neighbor bulk operations
    * added code coverage for neighbor bulk operations
    
    Signed-off-by: Nikola Dancejic <ndancejic@microsoft.com>

commit fbe3fc78dd308f570bc76b4838b3eee8c69f9828
Author: Nikola Dancejic <ndancejic@microsoft.com>
Date:   Fri May 24 17:57:45 2024 +0000

    [syncd] Addressing PR comments #1373
    
    Signed-off-by: Nikola Dancejic <ndancejic@microsoft.com>

commit a5b2bbb2f2404c9818a7050123a0dfc32299a144
Author: Nikola Dancejic <ndancejic@microsoft.com>
Date:   Tue May 28 01:16:46 2024 +0000

    Adding neighborBulkTest to syncd tests
    
    Signed-off-by: Nikola Dancejic <ndancejic@microsoft.com>

### CODE REVIEW

**Comment by bingwang-ms** [comment]
@Ndancejic Can you please check the failure in PR test?

**Comment by prsunny** [comment]
@Ndancejic , can you check the build failure? I thought this was already part of 202405. Lets get this resolved asap.

**Comment by Ndancejic** [comment]
Tested on a version without this change as well, test_pfcwd_shared_egress_acl_table.py is failing even without this. I would be happy to help debug the test issue, but since this change is critical for 202405 and is currently failing other PR tests maybe it would be good to merge since all other tests are passing

**Review by prsunny — APPROVED** [review]

**Comment by saiarcot895** [comment]
Test failure in here is for test_pfcwd_shared_egress_acl_table failing. This is seen starting from a sonic-swss commit (https://github.com/sonic-net/sonic-swss/commit/4f0d40c32ce18c281e09fd44891b2edf2e86b4ad).

This specific failure is fixing a failure in mux test cases. Because it is a net improvement (mux configuration uses the bulk APIs on 202405 branch, which apparently was missing in sairedis when the branch cutoff happened), I'm approving and force merging this PR.

**Review by saiarcot895 — APPROVED** [review]

**Comment by saiarcot895** [comment]
@bingwang-ms FYI

**Comment by nazariig** [comment]
@saiarcot895 i see that `buildimage` is pointing to some strange hash of `sairedis` instead of latest `202405`. Can you please fix that?

**Pull request merged**
