### PR TITLE
[SAI] Move SAI submodule to v1.13.3

### PR DESCRIPTION
**Pull request by kcudnik**

### CODE REVIEW

**Review by yxieca — APPROVED** [review]

**Comment by kcudnik** [comment]
Not sure if this error is caused by my change, sai pointer changed so maybe swss is not seeing everything

**Comment by kcudnik** [comment]
all recent PRs fail in the same place, seems like some hcanges in SWSS not passing

**Comment by kcudnik** [comment]
@rlhui error not related to PR if you want you can merge

**Comment by zhangyanzhao** [comment]
Can we merge this PR now? @rlhui . This is required by 202311 release. Thanks.

**Comment by kcudnik** [comment]
> Can we merge this PR now? @rlhui . This is required by 202311 release. Thanks.

just resolvd conflict

**Pull request merged**
