### PR TITLE
[CI]: Fix collect log error in azp template

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn <nazariig@nvidia.com>

**Cherry-Pick:** https://github.com/sonic-net/sonic-swss-common/pull/799

### CODE REVIEW

**Comment by nazariig** [comment]
@kcudnik can you please merge?

**Comment by StormLiangMS** [comment]
@nazariig  Cherry-Pick conflict, raise separate PR?

Do we need this for 202205 and 202305?

**Comment by nazariig** [comment]
> @nazariig Cherry-Pick conflict, raise separate PR?
> 
> Do we need this for 202205 and 202305?

@StormLiangMS yes, we do. I have raised a dedicated PRs.

**Pull request merged**
