### PR TITLE
Add retry on zmq functions if fail with EINTR.

### PR DESCRIPTION
**Pull request by mint570**
Fixed https://github.com/sonic-net/sonic-sairedis/issues/1106

### CODE REVIEW

**Comment by kcudnik** [comment]
please fix build errors

**Comment by mint570** [comment]
Build was fine but the vs test failed.
I didn't know that the sairedis repo also run the vs test.

The vs test failure is most likely https://github.com/sonic-net/sonic-swss/issues/2330.
Recently we submitted https://github.com/sonic-net/sonic-swss/pull/2237, which added a few more pytests. Without the fix, vs test will almost guarantee fail.

Also, about code coverage, I don't think zmq is enabled in vs test. So after we fix the vs test, this PR might still fail in code coverage.

**Comment by mint570** [comment]
Correction.
https://github.com/sonic-net/sonic-swss/issues/2330 shouldn't be the issue for sairedis because coverage is not enabled here.
Will re-run the test and see.
I don't think zmq is enabled in vs docker. So this change should have zero impact on the vs test.

**Comment by kcudnik** [comment]
you dont need entire VS for testing, you can use unittests and test only zmqchannel class, check in sairedis/unitests/ directory

**Comment by mint570** [comment]
@kcudnik 
This PR is ready. Please take a look.

**Review by kcudnik — APPROVED** [review]

**Comment by mint570** [comment]
@kcudnik can this PR be merged now?

**Pull request merged**
