### PR TITLE
SAI submodule update to pick the sai-thrift support added to read VOQ counters 

### PR DESCRIPTION
**Pull request by saksarav-nokia**
Sai-thrift in SAI has been enhanced to read the VOQ counters and this PR updates the SAI sobmodule.

### CODE REVIEW

**Review by kcudnik — APPROVED** [review]

**Comment by saksarav-nokia** [comment]
@vmittal-msft

**Comment by gechiang** [comment]
@vmittal-msft do we need this for 202205, 202305, and 202311?  Please add the request labels and the MSFT ADO (number only).
@kcudnik who can merge this PR? Please help add the person that can approve and merge this. Thanks!

**Comment by kcudnik** [comment]
Sai-thrift in SAI has been enhanced to read the VOQ counters and this PR updates the SAI sobmodule

**Comment by saksarav-nokia** [comment]
> @saksarav-nokia cherry pick PR didn't pass PR checker. Please check!!!#1347

I see the following errors with Building swss and they are not related to my changes. Some one else needs to look at it.
Compile sonic swss

[View raw log](https://dev.azure.com/mssonic/be1b070f-be15-4154-aade-b1d3bfb17054/_apis/build/builds/471812/logs/88)

Making all in orchagent
make[3]: Entering directory '/__w/1/s/orchagent'
make[4]: Entering directory '/__w/1/s/orchagent'

g++ -DHAVE_CONFIG_H -I. -I.. -I ../lib -I .. -I ../warmrestart -I switch -I flex_counter -I debug_counter -I port -I pbh -I nhg -g -DNDEBUG  -std=c++14 -Wall -fPIC -Wno-write-strings -I/usr/include/swss -I/usr/include/libnl3 -Werror -Wno-reorder -Wcast-align -Wcast-qual -Wconversion -Wdisabled-optimization -Wextra -Wfloat-equal -Wformat=2 -Wformat-nonliteral -Wformat-security -Wformat-y2k -Wimport -Winit-self -Winvalid-pch -Wlong-long -Wmissing-field-initializers -Wmissing-format-attribute -Wno-aggregate-return -Wno-padded -Wno-switch-enum -Wno-unused-parameter -Wpacked -Wpointer-arith -Wredundant-decls -Wstack-protector -Wstrict-aliasing=3 -Wswitch -Wswitch-default -Wunreachable-code -Wunused -Wvariadic-macros -Wno-switch-default -Wno-long-long -Wno-redundant-decls -I /usr/include/sai  -Wdate-time -D_FORTIFY_SOURCE=2  -g -O2 -ffile-prefix-map=/__w/1/s=. -fstack-protector-strong -Wformat -Werror=format-security -c -o orchagent-orchdaemon.o `test -f 'orchdaemon.cpp' || echo './'`orchdaemon.cpp
In file included from orchdaemon.h:51,
                 from main.cpp:25:
dash/dashrouteorch.h:27:11: error: 'route' in namespace 'dash' does not name a type
   27 |     dash::route::Route metadata;
      |           ^~~~~
dash/dashrouteorch.h:46:11: error: 'route' in namespace 'dash' does not name a type
   46 |     dash::route::Route metadata;
      |           ^~~~~
make[4]: *** [Makefile:918: orchagent-main.o] Error 1
make[4]: *** Waiting for unfinished jobs....
In file included from orchdaemon.h:51,
                 from orchdaemon.cpp:5:
dash/dashrouteorch.h:27:11: error: 'route' in namespace 'dash' does not name a type
   27 |     dash::route::Route metadata;
      |           ^~~~~
dash/dashrouteorch.h:46:11: error: 'route' in namespace 'dash' does not name a type
   46 |     dash::route::Route metadata;
      |           ^~~~~
make[4]: *** [Makefile:974: orchagent-orchdaemon.o] Error 1
make[4]: Leaving directory '/__w/1/s/orchagent'
make[3]: *** [Makefile:2305: all-recursive] Error 1
make[3]: Leaving directory '/__w/1/s/orchagent'
make[2]: Leaving directory '/__w/1/s'
make[2]: *** [Makefile:420: all-recursive] Error 1
make[1]: *** [Makefile:352: all] Error 2
make[1]: Leaving directory '/__w/1/s'
dh_auto_build: error: make -j2 returned exit code 2
make: *** [debian/rules:22: build] Error 25
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

##[error]Bash exited with code '2'.
Finishing: Compile sonic swss

**Comment by kcudnik** [comment]
one task in swss pipeline on sairedis repo is not executing "download dash api" /sonic-sairedis/.azure-pipelines/build-swss-template.yml line 140, not sure why, im investigating

**Pull request merged**
