### PR TITLE
Add new functionality to syncd_init_common.sh, to use common sai.profile

### PR DESCRIPTION
**Pull request by noaOrMlnx**
Changed config_mlnx_syncd() functionality to use common sai.profile for all SKUs, then apply the specific SKU sai.profile on top of it, and remove duplications.

Why I did it
To have the ability to add common parameters to only 1 file instead of all SKUs.

### CODE REVIEW

**Review by nazariig — APPROVED** [review]

**Comment by kcudnik** [comment]
is this ready to merge ?

**Comment by noaOrMlnx** [comment]
Hi @kcudnik,
Yes, the PR is ready for merge. thanks!

**Comment by liat-grozovik** [comment]
@noaOrMlnx please check the checkers failures. without them passing we cannot move forward and merge. 10x

**Comment by noaOrMlnx** [comment]
@kcudnik checkers pass, can you please help with merging the PR?

**Comment by dprital** [comment]
@yxieca , Can you please cherry pick to 202311 ?

**Pull request merged**
