### PR TITLE
Fix for [EVPN] When MAC moves from remote end point to local, ASIC DB fields are not updated properly for the mac #11503Update NotificationProcessor.cpp

### PR DESCRIPTION
**Pull request by anilkpan**
Issue:
When a mac moves from remote to local, the local mac is set in ASIC db using hset, which updates common fields, but does not remove fields specific to remote mac.

Fix:
In case of a mac move event, remove the existing FDB entry from ASIC DB first and then set the new one.

### CODE REVIEW

**Review by dgsudharsan — CHANGES_REQUESTED** [review]
@anilkpan Can you please add UT for the coverage?

**Comment by dgsudharsan** [comment]
@kcudnik Can you please review?

**Review by kcudnik — APPROVED** [review]

**Comment by anilkpan** [comment]
I will work on adding the PTF test for mac move. ETA end of the month.

**Review by dgsudharsan — APPROVED** [review]

**Review by kcudnik — DISMISSED** [review]

**Comment by kcudnik** [comment]
please satisfy code coverage via unittests

**Comment by dgsudharsan** [comment]
> I will work on adding the PTF test for mac move. ETA end of the month.

Hi @anilkpan  Not sure if PTF tests will satisfy the coverage. I believe you need to add gtest here. Can you please check?

**Comment by kcudnik** [comment]
yes i was suggesting to add tests unittests here

**Comment by anilkpan** [comment]
> > I will work on adding the PTF test for mac move. ETA end of the month.
> 
> Hi @anilkpan Not sure if PTF tests will satisfy the coverage. I believe you need to add gtest here. Can you please check?

@dgsudharsan, i will start working  on adding the unittest next week.

**Comment by dgsudharsan** [comment]
@anilkpan Can you please provide ETA for UT?

**Comment by anilkpan** [comment]
@dgsudharsan, I have coded the gtest for this scenario. Is there a document that describes how to run the tests locally?

**Comment by kcudnik** [comment]
> > @dgsudharsan, I have coded the gtest for this scenario. Is there a document that describes how to run the tests locally?
> 
> @kcudnik Can you please help here?

to run locally go to the desired directory and type "make check" and it will run all tests

**Comment by anilkpan** [comment]
> > > @dgsudharsan, I have coded the gtest for this scenario. Is there a document that describes how to run the tests locally?
> > 
> > 
> > @kcudnik Can you please help here?
> 
> to run locally go to the desired directory and type "make check" and it will run all tests

Thanks @kcudnik, i will try this.

**Comment by anilkpan** [comment]
@kcudnik, 'make check' seems to need libsaimetadata.so.0, which was not built. Any ideas what I am missing?

make  check-TESTS
make[1]: Entering directory '/home/anilkpandey/sonic-buildimage/src/sonic-sairedis/lib'
/home/anilkpandey/sonic-buildimage/src/sonic-sairedis/lib/.libs/tests: error while loading shared libraries: libsaimetadata.so.0: cannot open shared object file: No such file or directory
FAIL: tests
==================
1 of 1 test failed
==================
Makefile:1592: recipe for target 'check-TESTS' failed

**Comment by kcudnik** [comment]
hmm, it should be build, can you type "make" first in top directory to build everyting ?

**Comment by dgsudharsan** [comment]
@anilkpan Can you please provide ETA of adding the coverage?

**Comment by anilkpan** [comment]
@dgsudharsan, I plan to add the test by end of next week.

**Comment by anilkpan** [comment]
need to check why the test is failing, will take few more days.

**Comment by anilkpan** [comment]
@dgsudharsan, The test is failing. Is the syslog or the core dump available for the test run so that I can debug the failure?

**Comment by dgsudharsan** [comment]
> @dgsudharsan, The test is failing. Is the syslog or the core dump available for the test run so that I can debug the failure?

@vivekrnv Can you please help here?

**Comment by vivekrnv** [comment]
> @dgsudharsan, The test is failing. Is the syslog or the core dump available for the test run so that I can debug the failure?

Hi, There must be a gtest binary/executable found after you run make. invoke the binary with gdb to drop into a shell. Set breakpoints in you code and debug. 
Additionally you can use --gtest_filter to only run the test you want to check.

**Comment by dgsudharsan** [comment]
@anilkpan Were you able to proceed? Can you please provide ETA?

**Comment by anilkpan** [comment]
Thanks @vivekrnv. 
@dgsudharsan, I have added the fix, checks look good so far.

**Review by dgsudharsan — APPROVED** [review]

**Comment by dgsudharsan** [comment]
@kcudnik  Can we merge this?

**Comment by dgsudharsan** [comment]
Request for 202211 branch

**Review by prsunny — APPROVED** [review]

**Comment by dgsudharsan** [comment]
@prsunny @yxieca Can we add label for 202205 and 202211 for this PR?

**Comment by yxieca** [comment]
@anilkpan, @dgsudharsan this change cannot be cherry-picked cleanly. Please open new PR.

**Comment by dgsudharsan** [comment]
@anilkpan Can you please raise a separate PR for 202205?

**Comment by anilkpan** [comment]
@dgsudharsan, working on it, ETA 12/22

**Pull request merged**
