### PR TITLE
[Dual-ToR] update sai.profile with SAI_ADDITIONAL_MAC_ENABLED attribute if corresponding arg passed to syncd

### PR DESCRIPTION
**Pull request by ayurkiv-nvda**
Signed-off-by: Andriy Yurkiv <ayurkiv@nvidia.com>

Update sai.profile with SAI_ADDITIONAL_MAC_ENABLED=1 if "dual_tor" attr is passed to syncd

### CODE REVIEW

**Review by stephenxs — APPROVED** [review]
LGTM

**Comment by ayurkiv-nvda** [comment]
Hello @stephenxs 
can you approve it again?
Your previous approval was dismissed because of rebase

**Review by stephenxs — APPROVED** [review]

**Comment by ayurkiv-nvda** [comment]
Hello @prsunny 
Can you please take a look?

**Comment by ayurkiv-nvda** [comment]
Hello @bingwang-ms 
Can you please take a look?
This PR is similar to https://github.com/sonic-net/sonic-sairedis/pull/1188

**Comment by bingwang-ms** [comment]
> Hello @bingwang-ms Can you please take a look? This PR is similar to #1188

May I know why do we need this attribute in dualtor scenario?

**Comment by ayurkiv-nvda** [comment]
> > Hello @bingwang-ms Can you please take a look? This PR is similar to #1188
> 
> May I know why do we need this attribute in dualtor scenario?

Need to add additional MAC to VLAN interface on Mellanox SPC-1. It is impossible on SPC-1, so we just add this additional MAC to FDB table, so traffic forwarding will work.

SAI use this SAI_ADDITIONAL_MAC_ENABLED attribute to make changes.

**Review by bingwang-ms — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@saiarcot895 @kcudnik can you please help to merge?

**Review by saiarcot895 — APPROVED** [review]

**Pull request merged**
