### PR TITLE
[syncd] Add pre match logic for acl entry (#1240)

### PR DESCRIPTION
**Pull request by kcudnik**
this will test scenario where we have 1 acl entry with counter and after warm boot 2 acl entries and 2 counters the same which could end up matching wrong acl counter and causing fail "object exist" on broadcom acl entry set, which will require improve pre match logic for acl entry

### CODE REVIEW

**Comment by kcudnik** [comment]
seems like build pipeline is broken here

**Comment by liuh-80** [comment]
@xumia @liushilongbuaa , the 202012 branch build pipeline seems break, could you please help check?

**Comment by saiarcot895** [comment]
sonic-net/sonic-swss-common#780 needs to be cherry-picked to 202012 branch (similar to how #1238 was cherry-picked to 202012 branch for this repo).

**Review by saiarcot895 — APPROVED** [review]

**Comment by kcudnik** [comment]
> [sonic-net/sonic-swss-common#780](https://github.com/sonic-net/sonic-swss-common/pull/780) needs to be cherry-picked to 202012 branch (similar to how #1238 was cherry-picked to 202012 branch for this repo).

who can fix this ?

**Comment by saiarcot895** [comment]
@kcudnik, I think this can be merged now?

**Pull request merged**
