### PR TITLE
[Marvell] platform renaming for innovium

### PR DESCRIPTION
**Pull request by krismarvell**
#### What i did
=======
this is one of the dependent set of PRs being raised for changing the innovium asic type to marvell-teralynx

#### How i did
=======
syncd based logging enablement inside syncd docker and its related asic type checks are modified as per the renaming

#### How to verify
==========
Verfify syncd docker configs are applied properly in teralynx platform

### CODE REVIEW

**Comment by krismarvell** [comment]
@kcudnik Can you pls help review ?

**Review by saiarcot895 — DISMISSED** [review]

**Review by kcudnik — APPROVED** [review]

**Review by kcudnik — DISMISSED** [review]

**Comment by lguohan** [comment]
@saiarcot895 , are you okay with this one?

**Review by saiarcot895 — APPROVED** [review]

**Comment by saiarcot895** [comment]
@krismarvell can you do another merge?

**Comment by krismarvell** [comment]
> @krismarvell can you do another merge?

Just done the rebase now

**Pull request merged**
