### PR TITLE
[nvidia] extend syncd start script to pick extra SAI profile values

### PR DESCRIPTION
**Pull request by stepanblyschak**
In order to achive functionality that allows other applications to write additional parameters to sai.profile to customize it's behaviour per need.

### CODE REVIEW

**Review by kcudnik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@kcudnik could you please help to merge and set label 'mellanox'?

**Comment by prsunny** [comment]
@liat-grozovik , i dont find a label "mellanox"

**Comment by liat-grozovik** [comment]
thanks, so probably can be skipped

**Comment by stepanblyschak** [comment]
@liat-grozovik @prsunny @kcudnik Request for 202211 (I have no permissions to add lables)

**Pull request merged**
