### PR TITLE
Skip ASIC_TEMPERATURE attributes from sairedis recording

### PR DESCRIPTION
**Pull request by saksarav-nokia**
Skip SAI_SWITCH_ATTR_TEMP_LIST, SAI_SWITCH_ATTR_MAX_TEMP and SAI_SWITCH_ATTR_AVERAGE_TEMP attributes from sairedis recording since they are polled in every polling interval

### CODE REVIEW

**Comment by saksarav-nokia** [comment]
@kcudnik , Please review

**Review by kcudnik — APPROVED** [review]

**Comment by saksarav-nokia** [comment]
@kcudnik , The following errors don't seem to be related to my changes. Could you please check?

2024-05-03T07:00:35.3530529Z [       OK ] ClientServerSai.MCAST_FDB_ENTRY (7 ms)
2024-05-03T07:00:35.3530896Z [ RUN      ] ClientServerSai.NEIGHBOR_ENTRY
2024-05-03T07:00:35.3588404Z Assertion failed: pfd.revents & POLLIN (src/signaler.cpp:265)
2024-05-03T07:00:35.6283404Z /bin/bash: line 6: 24157 Aborted                 (core dumped) ${dir}$tst
2024-05-03T07:00:35.6310396Z FAIL: tests
2024-05-03T07:00:35.6333449Z ===================
2024-05-03T07:00:35.6333615Z 1 of 2 tests failed
2024-05-03T07:00:35.6333720Z ===================
2024-05-03T07:00:35.6344952Z make[3]: Leaving directory '/__w/1/s/unittest/lib'
2024-05-03T07:00:35.6345307Z make[2]: Leaving directory '/__w/1/s/unittest/lib'
2024-05-03T07:00:35.6352726Z make[3]: *** [Makefile:1975: check-TESTS] Error 1
2024-05-03T07:00:35.6353348Z make[2]: *** [Makefile:2101: check-am] Error 2
2024-05-03T07:00:35.6354243Z make[1]: *** [Makefile:405: check-recursive] Error 1
2024-05-03T07:00:35.6360517Z make[1]: Leaving directory '/__w/1/s/unittest'
2024-05-03T07:00:35.6366782Z make: *** [Makefile:460: check-recursive] Error 1
2024-05-03T07:00:35.6380667Z 
2024-05-03T07:00:35.6454915Z ##[error]Bash exited with code '2'.
2024-05-03T07:00:35.6539806Z ##[section]Finishing: Run sonic sairedis unit tests

**Comment by kcudnik** [comment]
This error seems to be related to zmq

**Comment by kcudnik** [comment]
no issue now :)

**Review by kcudnik — APPROVED** [review]

**Comment by kcudnik** [comment]
i'm wondering whether not move to to some config file, or add sairedis API for OA  to make control what's recorded or not

**Pull request merged**
