### PR TITLE
add if statement for module control mode support

### PR DESCRIPTION
**Pull request by dbarashinvd**
#### Why I did it
Feature - CMIS management

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
update syncd init common script to add module control profile content into sai.profile file

#### How to verify it
manually check sai.profile on a supporting switch (MSFT SKU) and verify module control profile content in it

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by kcudnik — APPROVED** [review]

**Comment by kcudnik** [comment]
Please add description

**Comment by dbarashinvd** [comment]
> Please add description

thanks. I did.

**Comment by xincunli-sonic** [comment]
PR is draft.

**Review by kcudnik — APPROVED** [review]

**Review by prgeor — APPROVED** [review]

**Comment by kcudnik** [comment]
is this still a draft or can be merged ?

**Comment by liat-grozovik** [comment]
@kcudnik can you please help to merge this PR?

**Pull request merged**
