### PR TITLE
Check MDIO server thread joinable before join the thread

### PR DESCRIPTION
**Pull request by jiahua-wang**
This PR is to address the issue [syncd crash observed during sonic-mgmt reboot tests #17346](https://github.com/sonic-net/sonic-buildimage/issues/17346)

### CODE REVIEW

**Comment by kcudnik** [comment]
Is the root case already known? Was it double joij?

**Comment by jiahua-wang** [comment]
Double join could be an explanation. More likely scenario is that m_taskThread is not joinable because after MdioIpcServer constructor startMdioThread() was not called or because startMdioThread() failed. @kenneth-arista can provide more test details.

**Comment by kcudnik** [comment]
> Double join could be an explanation. More likely scenario is that m_taskThread is not joinable because after MdioIpcServer constructor startMdioThread() was not called or because startMdioThread() failed. @kenneth-arista can provide more test details.

Can you investigate which exactly scenario is that ?

**Comment by kenneth-arista** [comment]
> > Double join could be an explanation. More likely scenario is that m_taskThread is not joinable because after MdioIpcServer constructor startMdioThread() was not called or because startMdioThread() failed. @kenneth-arista can provide more test details.
> 
> Can you investigate which exactly scenario is that ?

Unfortunately, I don't have all the logs when the problem occurred before integrating Jiahua's patch. Prior to the patch, I would often seen several syncd core files after each full sonic-mgmt test runs. I suspect these crashes are triggered in tests involving reboot.

**Comment by kenneth-arista** [comment]
I recall that a syncd crash was observed once during sonic-mgmt `override_config_table` tests.

**Comment by jiahua-wang** [comment]
This patch will address both cases of double join and thread not starting properly.

**Review by kcudnik — APPROVED** [review]

**Comment by rlhui** [comment]
@jiahua-wang  - please update the branch? thanks

**Review by kcudnik — APPROVED** [review]

**Comment by jiahua-wang** [comment]
@kcudnik @rlhui @judyjoseph  All checks were passed when I created the PR for the first time. After I merged other commits, 2 checks always fail at the place not related to my code change. Should I close this one and create another one with the same code change?

**Comment by kcudnik** [comment]
All passed do you want me to merge?

**Comment by jiahua-wang** [comment]
@kcudnik Please merge.

**Pull request merged**
