### PR TITLE
[ASAN]Increasing the watchdog timeout for ASAN builds

### PR DESCRIPTION
**Pull request by dgsudharsan**
Currently, when testing builds with ASAN on lower CPU systems, it takes sometimes for switch init to complete due to the additional overhead associated with ASAN builds.  Hence we start noticing errors as below. To overcome this increasing the watchdog timeout for ASAN builds.

```
Apr 18 17:22:17.296659 arc-switch1004 NOTICE syncd#SDK: :- threadFunction: time span 30751 ms for 'create:SAI_OBJECT_TYPE_SWITCH:oid:0x21000000000000'
Apr 18 17:22:17.296659 arc-switch1004 ERR syncd#SDK: :- threadFunction: time span WD exceeded 30751 ms for create:SAI_OBJECT_TYPE_SWITCH:oid:0x21000000000000
Apr 18 17:22:17.296659 arc-switch1004 ERR syncd#SDK: :- logEventData: op: create, key: SAI_OBJECT_TYPE_SWITCH:oid:0x21000000000000
Apr 18 17:22:17.296659 arc-switch1004 ERR syncd#SDK: :- logEventData: fv: SAI_SWITCH_ATTR_INIT_SWITCH: true
Apr 18 17:22:17.296659 arc-switch1004 ERR syncd#SDK: :- logEventData: fv: SAI_SWITCH_ATTR_FDB_EVENT_NOTIFY: 0x5612d4214b20
Apr 18 17:22:17.296659 arc-switch1004 ERR syncd#SDK: :- logEventData: fv: SAI_SWITCH_ATTR_PORT_STATE_CHANGE_NOTIFY: 0x5612d4214b30
Apr 18 17:22:17.296659 arc-switch1004 ERR syncd#SDK: :- logEventData: fv: SAI_SWITCH_ATTR_SWITCH_SHUTDOWN_REQUEST_NOTIFY: 0x5612d4214b50

```

### CODE REVIEW

**Comment by kcudnik** [comment]
code still works without this fix, you just get extra logs, is this necessary ?

**Comment by dgsudharsan** [comment]
> code still works without this fix, you just get extra logs, is this necessary ?

@kcudnik. This throws error logs which will be caught by log analyzer and fail many tests. Hence it is better to fix here as it is expected with ASAN builds

**Comment by kcudnik** [comment]
thi seems more like workaround, since maybe SAI lib is too slow ?

**Comment by dgsudharsan** [comment]
> thi seems more like workaround, since maybe SAI lib is too slow ?

Its not a problem with SAI library. When we enable ASAN, it adds additional overhead which slows down the process (almost 2x https://github.com/google/sanitizers/wiki/AddressSanitizerPerformanceNumbers). Hence it is required to increase the timeout for ASAN specific builds.

**Review by oleksandrivantsiv — DISMISSED** [review]

**Review by kcudnik — APPROVED** [review]

**Comment by dgsudharsan** [comment]
@kcudnik  Can you please help to merge?

**Pull request merged**
