### PR TITLE
Do not enter vendor SAI critical section for counter polling/clearing operations

### PR DESCRIPTION
**Pull request by stephenxs**
**What I did**

Do not enter the vendor SAI critical section for counter-polling/-clearing operations.

**Why I did it**

There are two types of threads in syncd:
1. The syncd main thread in which the create/destroy/set/get SAI APIs are called
2. Flex counter threads in which counter-polling/-clearing APIs are called

The critical section in vendor SAI was introduced to protect vendors' SAI from being re-entered, which prevents the flex counter threads from running concurrently, and introduces latency for one flex counter thread when it's waiting for the critical section.
It is not necessary to enter a section in counter-polling/clearing operations since the objects' state won't be changed in that API.

**How I verified it**

Run regression test and observe counter-polling performance.

**Details if related**

### CODE REVIEW

**Review by Junchao-Mellanox — APPROVED** [review]

**Review by kcudnik — APPROVED** [review]

**Comment by bingwang-ms** [comment]
@stephenxs @kcudnik I would not include this change in 202405 branch as we are finishing the qualification for 202405. Please let me know if you think this is a must-have change for 202405.

**Comment by kcudnik** [comment]
I'm not able to answer that question, that change was made to fix counter pooling fix, I think it would b3 nic to have at least, please ask @stephenxs

**Comment by kperumalbfn** [comment]
@stephenxs Removing this PR from 202411 for now. Please confirm the resolution of the timeout issue you mentioned in the revert PR.

**Comment by kperumalbfn** [comment]
@stephenxs could you please fix the cherrypick conflict in 202411

**Comment by stephenxs** [comment]
> @stephenxs could you please fix the cherrypick conflict in 202411

Thanks @kperumalbfn 
we do not need it for any legacy branches for now. I removed all the flags.

**Comment by stephenxs** [comment]
@kperumalbfn could you check whether this PR is in 202411? it is reverted from master and you said it had been removed in 202411.

**Comment by bingwang-ms** [comment]
@kperumalbfn I checked 202411 branch and confirmed this change is in 202411 branch because PR was merged before 202411 got cut off. So we need to cherry-pick the revert PR #1450

**Pull request merged**
