### PR TITLE
Update SAI submodule to pick the voq counter support added in sai-thrift

### PR DESCRIPTION
**Pull request by saksarav-nokia**
Updated the SAI submodule to pick the sai-thrift changes made to support voq counters

### CODE REVIEW

**Comment by saksarav-nokia** [comment]
@kcudnik @vmittal-msft , please review this

**Review by kcudnik — APPROVED** [review]

**Comment by saksarav-nokia** [comment]
@kcudnik  @vmittal-msft , The test failures are not related to my changes. Can you restart the tests

**Comment by vmittal-msft** [comment]
@arlakshm @rlhui we are planning to have this for master only? and add to 202205 later. if so, we can cancel this PR. Please confirm.

**Comment by vmittal-msft** [comment]
@saksarav-nokia we have master PR merged for the same ?

**Comment by saksarav-nokia** [comment]
> @saksarav-nokia we have master PR merged for the same ?

Yes @vmittal-msft

**Comment by saksarav-nokia** [comment]
https://github.com/opencomputeproject/SAI/pull/1931
https://github.com/sonic-net/sonic-sairedis/pull/1332

**Review by kcudnik — APPROVED** [review]

**Comment by rlhui** [comment]
> @arlakshm @rlhui we are planning to have this for master only? and add to 202205 later. if so, we can cancel this PR. Please confirm.

@saksarav-nokia  - there's no plan to update this for 202205.  Please close this.

**Comment by saksarav-nokia** [comment]
closing as per Rita's request

**Pull request closed without merging**
