### PR TITLE
[vslib]: Add SAI_PORT_ATTR_OPER_SPEED get

### PR DESCRIPTION
**Pull request by Pterosaur**
Add `SAI_PORT_ATTR_OPER_SPEED ` get in vslib. 
If the `SAI_PORT_ATTR_OPER_STATUS` is DOWN, `SAI_PORT_ATTR_OPER_SPEED`  should be 0, otherwise its value comes from `/sys/class/net/eth{X}/speed`

Signed-off-by: Ze Gan <ganze718@gmail.com>

### CODE REVIEW

**Comment by Pterosaur** [comment]
@kcudnik  I think the failure in LGTM isn't introduced by this PR.

**Review by kcudnik — APPROVED** [review]

**Comment by Pterosaur** [comment]
@kcudnik Could you please merge this PR? Because it is needed by advancing swss.

**Comment by yxieca** [comment]
@Pterosaur there is conflict. Can you raise separate PR or suggesting dependencies?

**Comment by Pterosaur** [comment]
> @Pterosaur there is conflict. Can you raise separate PR or suggesting dependencies?

Create a separate PR for 202205.

**Pull request merged**
