### PR TITLE
[202012][VxLAN] VxLAN Tunnel Counters and Rates implementation

### PR DESCRIPTION
**Pull request by dgsudharsan**
Backport of https://github.com/sonic-net/sonic-sairedis/pull/886
Added Flex counter support for tunnel counters and rates implementation

### CODE REVIEW

**Review by kcudnik — APPROVED** [review]

**Comment by dgsudharsan** [comment]
@kcudnik Do we know the reason for LGTM failure? It says base commit not found.

**Comment by kcudnik** [comment]
yes, 202012 branch dont have uuid library in lgtm container, i will make PR for that

**Comment by dgsudharsan** [comment]
@kcudnik  Can we merge this? The checkers pass now

**Pull request merged**
