### PR TITLE
Revert "Ignore removing switch for mellanox platform due to known limitation (#1216)"

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
What I did?

This reverts commit acd57ae628a2c8f99851ce1a7c85bf154a88f972.

Why I did this?

This commit introduces a race condition with would cause syncd crash. The issue happens when:

1. Syncd.m_sn has been freed
2. SAI send a port state change notification which will access Syncd.m_sn ===> causes crash

### CODE REVIEW

**Review by kcudnik — APPROVED** [review]

**Comment by Junchao-Mellanox** [comment]
Hi @kcudnik , could you please help merge this?

**Pull request merged**
