### PR TITLE
[hash]: Extend VS lib with ECMP/LAG hash algorithm

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn [nazariig@nvidia.com](mailto:nazariig@nvidia.com)

**HLD:** https://github.com/sonic-net/SONiC/pull/1501

### CODE REVIEW

**Comment by nazariig** [comment]
@stepanblyschak FYI

**Review by kcudnik — APPROVED** [review]

**Review by stepanblyschak — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@kcudnik  could you please help to merge it?

**Comment by kcudnik** [comment]
merged master branch after success i will merge

**Comment by liushilongbuaa** [comment]
Already included in 202311. Don't need to cherry pick.

**Pull request merged**
